google.maps.__gjsload__('infowindow', function(_){var Eya=function(){this.h=new _.x.Set},Fya=function(a,b){if(1===a.h.size){var c=_.u(Array,"from").call(Array,_.u(a.h,"values").call(a.h))[0];c.jl!==b.jl&&(c.set("map",null),a.h.delete(c))}a.h.add(b)},OF=function(a){var b=this;this.N=a.lw;this.o=null;this.R=a.shouldFocus;this.h=_.sm("div");_.Nu(this.h,"default");this.h.style.position="absolute";this.h.style.left=this.h.style.top="0";a.yh.floatPane.appendChild(this.h);this.H=_.sm("div",this.h);this.D=_.sm("div",this.H);this.j=_.sm("div",this.D);this.j.setAttribute("role",
"dialog");this.j.tabIndex=-1;this.l=_.sm("div",this.j);_.Ura(this.h);_.$l(this.j,"gm-style-iw");_.$l(this.H,"gm-style-iw-a");_.$l(this.D,"gm-style-iw-t");_.$l(this.j,"gm-style-iw-c");_.$l(this.l,"gm-style-iw-d");_.ii.h&&(a.yc?this.j.style.paddingLeft=0:this.j.style.paddingRight=0,this.j.style.paddingBottom=0,this.l.style.overflow="scroll");NF(this,!1);_.J.Sa(this.h,"mousedown",_.$e);_.J.Sa(this.h,"mouseup",_.$e);_.J.Sa(this.h,"mousemove",_.$e);_.J.Sa(this.h,"pointerdown",_.$e);_.J.Sa(this.h,"pointerup",
_.$e);_.J.Sa(this.h,"pointermove",_.$e);_.J.Sa(this.h,"dblclick",_.$e);_.J.Sa(this.h,"click",_.$e);_.J.Sa(this.h,"touchstart",_.$e);_.J.Sa(this.h,"touchend",_.$e);_.J.Sa(this.h,"touchmove",_.$e);_.J.Tb(this.h,"contextmenu",this,this.yy);_.J.Tb(this.h,"wheel",this,_.$e);_.J.Tb(this.h,"mousewheel",this,_.Xe);_.J.Tb(this.h,"MozMousePixelScroll",this,_.Xe);this.J=new _.$p({Oi:new _.R(8,8),oh:new _.cg(14,14),offset:new _.R(-6,-6)});this.j.appendChild(this.J.element);_.J.Sa(this.J.element,"click",function(c){_.$e(c);
_.J.trigger(b,"closeclick");b.set("open",!1)});this.m=null;this.F=this.L=!1;this.C=new _.Oh(function(){!b.L&&b.get("content")&&b.get("visible")&&(_.J.trigger(b,"domready"),b.L=!0)},0);this.M=_.J.Sa(this.h,"keydown",function(c){"Escape"!==c.key&&"Esc"!==c.key||!b.j.contains(document.activeElement)||(c.stopPropagation(),_.J.trigger(b,"closeclick"),b.set("open",!1))})},Gya=function(a){var b=!!a.get("open"),c=a.get("content");c=b?c:null;if(c==a.m)NF(a,b&&a.get("position"));else{if(a.m){var d=a.m.parentNode;
d==a.l&&d.removeChild(a.m)}c&&(a.L=!1,a.l.appendChild(c));NF(a,b&&a.get("position"));a.m=c;PF(a)}},Hya=function(a){var b=a.get("pixelOffset")||new _.cg(0,0),c=new _.cg(a.j.offsetWidth,a.j.offsetHeight);a=-b.height+c.height+11+60;var d=b.height+60,e=-b.width+c.width/2+60;c=b.width+c.width/2+60;0>b.height&&(d-=b.height);return{top:a,bottom:d,left:e,right:c}},NF=function(a,b){a.h.style.visibility=b?"":"hidden";b&&a.R&&(a.focus(),a.R=!1);b?Iya(a):a.F=!1},PF=function(a){var b=a.get("layoutPixelBounds"),
c=a.get("pixelOffset");var d=a.get("maxWidth")||648;var e=a.get("minWidth")||0;c?(b?(c=b.Ga-b.Aa-(11+-c.height),b=b.Ia-b.Ea-6,240<=b&&(b-=120),240<=c&&(c-=120)):(b=648,c=654),b=Math.min(b,d),b=Math.max(e,b),b=Math.max(0,b),c=Math.max(0,c),d={yf:new _.cg(b,c),minWidth:e}):d=null;if(e=d)d=e.yf,e=e.minWidth,a.j.style.maxWidth=_.Gl(d.width),a.j.style.maxHeight=_.Gl(d.height),a.j.style.minWidth=_.Gl(e),a.l.style.maxHeight=_.ii.h?_.Gl(d.height-18):_.Gl(d.height-36),QF(a),a.C.start()},Iya=function(a){!a.F&&
a.get("open")&&a.get("visible")&&a.get("position")&&(_.J.trigger(a,"visible"),a.F=!0)},QF=function(a){var b=a.get("position");if(b&&a.get("pixelOffset")){var c=Hya(a),d=b.x-c.left,e=b.y-c.top,f=b.x+c.right;c=b.y+c.bottom;_.rm(a.H,b);b=a.get("zIndex");_.tm(a.h,_.he(b)?b:e+60);a.set("pixelBounds",_.Rh(d,e,f,c))}},Jya=function(a,b){var c=a.__gm;a=c.get("panes");c=c.get("innerContainer");b={yh:a,yc:_.ns.yc(),lw:c,shouldFocus:b};return new OF(b)},RF=function(a,b,c){var d=this;this.H=a;this.C=!0;this.Ya=
this.m=this.l=null;this.h=[];var e=a.get("shouldFocus");this.o=Jya(b,e);var f=b.__gm;(e=b instanceof _.jf)&&c?c.then(function(l){d.C&&(d.l=l,d.Ya=new _.VB(function(m){d.m=new _.mp(b,l,m,function(){});l.hb(d.m);return d.m}),d.Ya.bindTo("latLngPosition",a,"position"),Kya(d))}):(this.Ya=new _.VB,this.Ya.bindTo("latLngPosition",a,"position"),this.Ya.bindTo("center",f,"projectionCenterQ"),this.Ya.bindTo("zoom",f),this.Ya.bindTo("offset",f),this.Ya.bindTo("projection",b),this.Ya.bindTo("focus",b,"position"),
Kya(this));this.D=e?a.Kg()?"Ia":"Id":null;this.F=e?a.Kg()?148284:148285:null;var g=new _.WB(["scale"],"visible",function(l){return null==l||.3<=l});this.Ya&&g.bindTo("scale",this.Ya);var h=this.o;h.set("logAsInternal",a.Kg());h.bindTo("ariaLabel",a);h.bindTo("zIndex",a);h.bindTo("layoutPixelBounds",f,"pixelBounds");h.bindTo("disableAutoPan",a);h.bindTo("pendingFocus",a);h.bindTo("maxWidth",a);h.bindTo("minWidth",a);h.bindTo("content",a);h.bindTo("pixelOffset",a);h.bindTo("visible",g);this.j=new _.Oh(function(){if(b instanceof
_.jf)if(d.l){var l=a.get("position");l&&_.Uha(b,d.l,new _.Bf(l),Hya(h))}else c.then(function(){return d.j.start()});else(l=h.get("pixelBounds"))?_.J.trigger(f,"pantobounds",l):d.j.start()},150);if(e){var k=null;this.h.push(_.J.Kb(a,"position_changed",function(){var l=a.get("position");!l||a.get("disableAutoPan")||l.equals(k)||(d.j.start(),k=l)}))}else a.get("disableAutoPan")||this.j.start();h.set("open",!0);this.h.push(_.J.addListener(h,"domready",function(){a.trigger("domready")}));this.h.push(_.J.addListener(h,
"visible",function(){a.trigger("visible")}));this.h.push(_.J.addListener(h,"closeclick",function(){a.close();a.trigger("closeclick")}));this.h.push(_.J.Kb(a,"pixelposition_changed",function(){Lya(d)}));this.D&&_.Q(b,this.D);this.F&&_.O(b,this.F)},Kya=function(a){a.Ya&&a.h.push(_.J.Kb(a.Ya,"pixelposition_changed",function(){Lya(a)}))},Lya=function(a){var b=a.H.get("pixelPosition")||a.Ya&&a.Ya.get("pixelPosition");a.o.set("position",b)},Mya=function(a,b,c){return b instanceof _.jf?new RF(a,b,c):new RF(a,
b)},Nya=function(a){a=a.__gm;return a.IW_AUTO_CLOSER=a.IW_AUTO_CLOSER||new Eya};_.B(OF,_.K);_.n=OF.prototype;_.n.ariaLabel_changed=function(){var a=this.get("ariaLabel");a?this.j.setAttribute("aria-label",a):this.j.removeAttribute("aria-label")};_.n.open_changed=function(){Gya(this)};_.n.content_changed=function(){Gya(this)};
_.n.pendingFocus_changed=function(){this.get("pendingFocus")&&(this.get("open")&&this.get("visible")&&this.get("position")?_.mi(this.j,!0):console.warn("Setting focus on InfoWindow was ignored. This is most likely due to InfoWindow not being visible yet."),this.set("pendingFocus",!1))};
_.n.dispose=function(){var a=this;setTimeout(function(){document.activeElement&&document.activeElement!==document.body||(a.o&&a.o!==document.body?_.mi(a.o,!0)||_.mi(a.N,!0):_.mi(a.N,!0))});this.M&&_.J.removeListener(this.M);this.h.parentNode.removeChild(this.h);this.C.stop();this.C.dispose()};_.n.pixelOffset_changed=function(){var a=this.get("pixelOffset")||new _.cg(0,0);this.D.style.right=_.Gl(-a.width);this.D.style.bottom=_.Gl(-a.height+11);PF(this)};_.n.layoutPixelBounds_changed=function(){PF(this)};
_.n.position_changed=function(){this.get("position")?(QF(this),NF(this,!!this.get("open"))):NF(this,!1)};_.n.zIndex_changed=function(){QF(this)};_.n.visible_changed=function(){_.Ku(this.h,this.get("visible"));this.C.start();this.get("visible")?Iya(this):this.F=!1};_.n.yy=function(a){for(var b=!1,c=this.get("content"),d=a.target;!b&&d;)b=d==c,d=d.parentNode;b?_.Xe(a):_.Ze(a)};
_.n.focus=function(){this.o=document.activeElement;var a;_.ii.D&&(a=this.l.getBoundingClientRect());if(this.get("disableAutoPan"))_.mi(this.j,!0);else{var b=_.kga(this.l);if(b.length){b=b[0];a=a||this.l.getBoundingClientRect();var c=b.getBoundingClientRect();_.mi(c.bottom<=a.bottom&&c.right<=a.right?b:this.j,!0)}else _.mi(this.J.element,!0)}};RF.prototype.close=function(){if(this.C){this.C=!1;for(var a=_.A(this.h),b=a.next();!b.done;b=a.next())_.J.removeListener(b.value);this.h.length=0;this.j.stop();this.j.dispose();this.l&&this.m&&this.l.ig(this.m);a=this.o;a.unbindAll();a.set("open",!1);a.dispose();this.Ya&&this.Ya.unbindAll()}};_.We("infowindow",{cv:function(a){var b=null;_.J.Kb(a,"map_changed",function d(){var e=a.get("map");b&&(b.wq.h.delete(a),b.Sy.close(),b=null);if(e){var f=e.__gm;f.get("panes")?(b={Sy:Mya(a,e,e instanceof _.jf?f.h.then(function(g){return g.Ma}):void 0),wq:Nya(e)},Fya(b.wq,a)):_.J.addListenerOnce(f,"panes_changed",d)}})}});});
